workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      node: 18.17.0
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials
      vars:
        BUNDLE_ID: "com.gigglz.app"
        APP_STORE_APP_ID: "6740466638"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.gigglz.app

    integrations:
      app_store_connect: Gigglz API Key

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build Next.js
        script: |
          npm run build

      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios

      - name: Install CocoaPods dependencies
        script: |
          cd ios/App && pod install

      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "App" \
            --config "Release"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        expire_build_submitted_for_review: true
