workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      groups:
        - ios_credentials
      vars:
        XCODE_WORKSPACE: "App.xcworkspace"
        XCODE_SCHEME: "App"
        APP_STORE_APP_ID: 6740466638
        BUNDLE_ID: "com.gigglz.app"
      node: 20.11.0
      xcode: latest
      cocoapods: default

    scripts:
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates

      - name: Install npm dependencies
        script: |
          npm install

      - name: Build Next.js
        script: |
          npm run build

      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios

      - name: Install CocoaPods dependencies
        script: |
          cd ios/App && pod install

      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles

      - name: Build ipa for distribution
        script: |
          cd $CM_BUILD_DIR/ios/App
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - ios/App/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
